### ISSUE TITLE
有新的释放内存的方法吗？

### ISSUE THREAD

**Issue by owllight11** [UNeedCryDear/tets_onnxruntime_gpu_memory#1]
您好，我想要在运行完程序后手动释放内存和GPU显存，但是使用`delete _OrtSession`无法完全释放，然后在onnx下看到了您的issue，试了您的demo使用`Ort::detail::OrtRelease`似乎效果和delete是一致的，想问下您现在有尝试过其他方法来释放内存和显存吗？

**Comment by UNeedCryDear** [comment]
没有，官方也没有告知释放方案，只是说ORT本身的特性。

**Comment by owllight11** [comment]
好的，谢谢您的回答
